[package]
name = "example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
verify_attr = { path = "../verify_attr" }

[lib]
path = "lib.rs"
proc-macro = true
